application: fssnippets
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/mail/snippets@.*fssnippets\.appspotmail\.com 
  script: receive_email.py

- url: .*
  script: main.py
    
inbound_services:
- mail