application: fssnippets
version: 1
runtime: python
api_version: 1

handlers:
- url: .*
  script: main.py

- url: /_ah/mail/snippet@.*app-id\.appspotmail\.com 
  script: receive_email.py 
  login: admin
    
inbound_services:
- mail